-- =============================================================
-- Supabase 테이블 생성 SQL
-- Supabase Dashboard → SQL Editor 에서 실행하세요.
-- =============================================================

-- 1. 메인 테이블: 생산 기록
CREATE TABLE IF NOT EXISTS production_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lumi_sn TEXT NOT NULL,
    solity_sn TEXT NOT NULL,
    production_time TEXT NOT NULL,
    operator_name TEXT DEFAULT '',
    note TEXT DEFAULT '',
    CONSTRAINT lumi_sn_not_empty CHECK (length(trim(lumi_sn)) > 0),
    CONSTRAINT solity_sn_not_empty CHECK (length(trim(solity_sn)) > 0),
    CONSTRAINT different_sns CHECK (lumi_sn <> solity_sn),
    UNIQUE (lumi_sn, solity_sn)
);

CREATE INDEX IF NOT EXISTS idx_production_records_time
    ON production_records (production_time DESC);

CREATE INDEX IF NOT EXISTS idx_production_records_lumi_sn
    ON production_records (lumi_sn);

CREATE INDEX IF NOT EXISTS idx_production_records_solity_sn
    ON production_records (solity_sn);

-- 2. SN 사용 추적 테이블
CREATE TABLE IF NOT EXISTS used_sn_codes (
    sn_value TEXT PRIMARY KEY,
    record_id BIGINT NOT NULL REFERENCES production_records(id) ON DELETE CASCADE,
    sn_role TEXT NOT NULL CHECK (sn_role IN ('lumi', 'solity'))
);

-- 3. 앱 설정 테이블
CREATE TABLE IF NOT EXISTS app_settings (
    settings_key TEXT PRIMARY KEY,
    settings_value TEXT NOT NULL
);

-- 4. RLS(Row Level Security) 활성화 및 정책 설정
ALTER TABLE production_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE used_sn_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on production_records"
    ON production_records FOR ALL
    USING (true) WITH CHECK (true);

CREATE POLICY "Allow all on used_sn_codes"
    ON used_sn_codes FOR ALL
    USING (true) WITH CHECK (true);

CREATE POLICY "Allow all on app_settings"
    ON app_settings FOR ALL
    USING (true) WITH CHECK (true);

-- 5. Lumi SN 목록 테이블
CREATE TABLE IF NOT EXISTS lumi_sn_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sn_value TEXT NOT NULL UNIQUE,
    uploaded_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_lumi_sn_list_sn_value
    ON lumi_sn_list (sn_value);

ALTER TABLE lumi_sn_list ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on lumi_sn_list"
    ON lumi_sn_list FOR ALL
    USING (true) WITH CHECK (true);

-- 6. 기본 설정값 삽입
INSERT INTO app_settings (settings_key, settings_value)
VALUES
    ('first_qr_length', '0'),
    ('second_qr_length', '0')
ON CONFLICT (settings_key) DO NOTHING;
