-- =============================================================
-- Supabase 테이블 생성 및 마이그레이션 SQL (Aqara SN Matching Tool)
-- Supabase Dashboard → SQL Editor 에서 실행하세요.
-- =============================================================

-- [기존 테이블 구조 마이그레이션]
-- 1. production_records 테이블에 deleted_at 컬럼 추가 (없는 경우만)
ALTER TABLE production_records ADD COLUMN IF NOT EXISTS deleted_at TEXT DEFAULT NULL;

-- 2. 기존 복합 UNIQUE 제약조건 삭제 (개별 UNIQUE 제약으로 변경하기 위함)
ALTER TABLE production_records DROP CONSTRAINT IF EXISTS production_records_lumi_sn_solity_sn_key;

-- 3. 개별 UNIQUE 제약조건 추가 (중복 등록 원천 방지)
-- 주의: 기존 테이블에 이미 중복된 Lumi SN 또는 Solity SN이 있다면 이 단계에서 오류가 발생할 수 있습니다. 
-- 그 경우 중복된 행을 삭제한 후 다시 실행해 주세요.
ALTER TABLE production_records DROP CONSTRAINT IF EXISTS production_records_lumi_sn_key;
ALTER TABLE production_records ADD CONSTRAINT production_records_lumi_sn_key UNIQUE (lumi_sn);

ALTER TABLE production_records DROP CONSTRAINT IF EXISTS production_records_solity_sn_key;
ALTER TABLE production_records ADD CONSTRAINT production_records_solity_sn_key UNIQUE (solity_sn);


-- [테이블 생성]
-- 1. 메인 테이블: 생산 기록 (신규 설치용)
CREATE TABLE IF NOT EXISTS production_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lumi_sn TEXT NOT NULL UNIQUE,
    solity_sn TEXT NOT NULL UNIQUE,
    production_time TEXT NOT NULL,
    operator_name TEXT DEFAULT '',
    note TEXT DEFAULT '',
    deleted_at TEXT DEFAULT NULL,
    CONSTRAINT lumi_sn_not_empty CHECK (length(trim(lumi_sn)) > 0),
    CONSTRAINT solity_sn_not_empty CHECK (length(trim(solity_sn)) > 0),
    CONSTRAINT different_sns CHECK (lumi_sn <> solity_sn)
);

CREATE INDEX IF NOT EXISTS idx_production_records_time
    ON production_records (production_time DESC);

CREATE INDEX IF NOT EXISTS idx_production_records_lumi_sn
    ON production_records (lumi_sn);

CREATE INDEX IF NOT EXISTS idx_production_records_solity_sn
    ON production_records (solity_sn);

-- 2. SN 사용 추적 테이블 (used_sn_codes)
CREATE TABLE IF NOT EXISTS used_sn_codes (
    sn_value TEXT PRIMARY KEY,
    record_id BIGINT NOT NULL REFERENCES production_records(id) ON DELETE CASCADE,
    sn_role TEXT NOT NULL CHECK (sn_role IN ('lumi', 'solity'))
);

-- 3. 앱 설정 테이블 (app_settings)
CREATE TABLE IF NOT EXISTS app_settings (
    settings_key TEXT PRIMARY KEY,
    settings_value TEXT NOT NULL
);

-- 4. Lumi SN 사전 등록 테이블 (lumi_product_sn)
CREATE TABLE IF NOT EXISTS lumi_product_sn (
    lumi_sn TEXT PRIMARY KEY,
    time TEXT DEFAULT ''
);


-- [RLS 및 정책 설정]
-- RLS 활성화
ALTER TABLE production_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE used_sn_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE lumi_product_sn ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제 후 재생성 (오류 방지)
DROP POLICY IF EXISTS "Allow all on production_records" ON production_records;
CREATE POLICY "Allow all on production_records"
    ON production_records FOR ALL
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on used_sn_codes" ON used_sn_codes;
CREATE POLICY "Allow all on used_sn_codes"
    ON used_sn_codes FOR ALL
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on app_settings" ON app_settings;
CREATE POLICY "Allow all on app_settings"
    ON app_settings FOR ALL
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on lumi_product_sn" ON lumi_product_sn;
CREATE POLICY "Allow all on lumi_product_sn"
    ON lumi_product_sn FOR ALL
    USING (true) WITH CHECK (true);


-- [기본 데이터 설정]
INSERT INTO app_settings (settings_key, settings_value)
VALUES
    ('first_qr_length', '0'),
    ('second_qr_length', '0')
ON CONFLICT (settings_key) DO NOTHING;


-- [RPC 함수 정의]
-- 7. RPC 함수: 매칭 정보 트랜잭션 저장 (원자성 확보)
CREATE OR REPLACE FUNCTION create_production_match(
    p_lumi_sn TEXT,
    p_solity_sn TEXT,
    p_production_time TEXT,
    p_operator_name TEXT,
    p_note TEXT
) RETURNS jsonb AS $$
DECLARE
    v_record_id BIGINT;
    v_result jsonb;
BEGIN
    -- 1. production_records에 삽입
    INSERT INTO production_records (lumi_sn, solity_sn, production_time, operator_name, note)
    VALUES (p_lumi_sn, p_solity_sn, p_production_time, p_operator_name, p_note)
    RETURNING id INTO v_record_id;

    -- 2. used_sn_codes에 삽입
    INSERT INTO used_sn_codes (sn_value, record_id, sn_role)
    VALUES 
        (p_lumi_sn, v_record_id, 'lumi'),
        (p_solity_sn, v_record_id, 'solity');

    -- 3. 결과 반환값 구성
    v_result := jsonb_build_object(
        'id', v_record_id,
        'lumi_sn', p_lumi_sn,
        'solity_sn', p_solity_sn,
        'production_time', p_production_time,
        'operator_name', p_operator_name,
        'note', p_note
    );
    
    RETURN v_result;
END;
$$ LANGUAGE plpgsql;

-- 8. RPC 함수: Lumi SN 백리스트 트랜잭션 갱신 (전체 삭제 및 대량 삽입)
CREATE OR REPLACE FUNCTION replace_lumi_product_sn(p_rows jsonb) RETURNS void AS $$
BEGIN
    -- 테이블 비우기
    DELETE FROM lumi_product_sn;
    
    -- 대량 삽입 실행
    INSERT INTO lumi_product_sn (lumi_sn, time)
    SELECT 
        (value->>'lumi_sn')::TEXT, 
        COALESCE(value->>'time', '')::TEXT
    FROM jsonb_array_elements(p_rows);
END;
$$ LANGUAGE plpgsql;
