-- =============================================================
-- Supabase 테이블 생성 및 마이그레이션 SQL (Aqara SN Matching Tool)
-- Supabase Dashboard → SQL Editor 에서 실행하세요.
-- =============================================================

-- [기존 테이블 구조 마이그레이션]
-- 1. production_records 테이블에 deleted_at 컬럼 추가 (없는 경우만)
ALTER TABLE production_records ADD COLUMN IF NOT EXISTS deleted_at TEXT DEFAULT NULL;

-- 2. 기존 복합 UNIQUE 제약조건 삭제 (개별 UNIQUE 제약으로 변경하기 위함)
ALTER TABLE production_records DROP CONSTRAINT IF EXISTS production_records_lumi_sn_solity_sn_key;

-- 3. 개별 UNIQUE 제약조건 추가 (중복 등록 원천 방지)
-- 주의: 기존 테이블에 이미 중복된 Lumi SN 또는 Solity SN이 있다면 이 단계에서 오류가 발생할 수 있습니다. 
-- 그 경우 중복된 행을 삭제한 후 다시 실행해 주세요.
ALTER TABLE production_records DROP CONSTRAINT IF EXISTS production_records_lumi_sn_key;
ALTER TABLE production_records ADD CONSTRAINT production_records_lumi_sn_key UNIQUE (lumi_sn);

ALTER TABLE production_records DROP CONSTRAINT IF EXISTS production_records_solity_sn_key;
ALTER TABLE production_records ADD CONSTRAINT production_records_solity_sn_key UNIQUE (solity_sn);


-- [테이블 생성]
-- 1. 메인 테이블: 생산 기록 (신규 설치용)
CREATE TABLE IF NOT EXISTS production_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lumi_sn TEXT NOT NULL UNIQUE,
    solity_sn TEXT NOT NULL UNIQUE,
    production_time TEXT NOT NULL,
    operator_name TEXT DEFAULT '',
    note TEXT DEFAULT '',
    deleted_at TEXT DEFAULT NULL,
    CONSTRAINT lumi_sn_not_empty CHECK (length(trim(lumi_sn)) > 0),
    CONSTRAINT solity_sn_not_empty CHECK (length(trim(solity_sn)) > 0),
    CONSTRAINT different_sns CHECK (lumi_sn <> solity_sn)
);

CREATE INDEX IF NOT EXISTS idx_production_records_time
    ON production_records (production_time DESC);

CREATE INDEX IF NOT EXISTS idx_production_records_lumi_sn
    ON production_records (lumi_sn);

CREATE INDEX IF NOT EXISTS idx_production_records_solity_sn
    ON production_records (solity_sn);

-- 2. SN 사용 추적 테이블 (used_sn_codes)
CREATE TABLE IF NOT EXISTS used_sn_codes (
    sn_value TEXT PRIMARY KEY,
    record_id BIGINT NOT NULL REFERENCES production_records(id) ON DELETE CASCADE,
    sn_role TEXT NOT NULL CHECK (sn_role IN ('lumi', 'solity'))
);

-- 3. 앱 설정 테이블 (production_app_settings)
--    이 Supabase는 여러 프로젝트가 공유하므로 'production' 접두사를 붙인다.
CREATE TABLE IF NOT EXISTS production_app_settings (
    settings_key TEXT PRIMARY KEY,
    settings_value TEXT NOT NULL
);

-- 4. Lumi SN 사전 등록 테이블 (lumi_product_sn)
CREATE TABLE IF NOT EXISTS lumi_product_sn (
    lumi_sn TEXT PRIMARY KEY,
    time TEXT DEFAULT ''
);


-- [RLS 및 정책 설정]
-- RLS 활성화
ALTER TABLE production_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE used_sn_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE production_app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE lumi_product_sn ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제 후 재생성 (오류 방지)
DROP POLICY IF EXISTS "Allow all on production_records" ON production_records;
CREATE POLICY "Allow all on production_records"
    ON production_records FOR ALL
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on used_sn_codes" ON used_sn_codes;
CREATE POLICY "Allow all on used_sn_codes"
    ON used_sn_codes FOR ALL
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on production_app_settings" ON production_app_settings;
CREATE POLICY "Allow all on production_app_settings"
    ON production_app_settings FOR ALL
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on lumi_product_sn" ON lumi_product_sn;
CREATE POLICY "Allow all on lumi_product_sn"
    ON lumi_product_sn FOR ALL
    USING (true) WITH CHECK (true);


-- [기본 데이터 설정]
INSERT INTO production_app_settings (settings_key, settings_value)
VALUES
    ('first_qr_length', '0'),
    ('second_qr_length', '0')
ON CONFLICT (settings_key) DO NOTHING;

-- Solity SN 형식 규칙 (설정 페이지에서 변경 가능)
--   길이 0 / 접두사 빈값 / 접미사 빈값 = 해당 항목 검사 안 함
INSERT INTO production_app_settings (settings_key, settings_value)
VALUES
    ('solity_sn_length', '13'),
    ('solity_sn_prefix', 'AK'),
    ('solity_sn_suffixes', 'TAK,TAS')
ON CONFLICT (settings_key) DO NOTHING;


-- [RPC 함수 정의]
-- 7. RPC 함수: 매칭 정보 트랜잭션 저장 → 아래 [출하 동기화] 섹션에서 정의한다.
--    (shipped_devices 기록이 추가되어 해당 섹션으로 통합됨)

-- 8. RPC 함수: Lumi SN 백리스트 트랜잭션 갱신 (전체 삭제 및 대량 삽입)
CREATE OR REPLACE FUNCTION replace_lumi_product_sn(p_rows jsonb) RETURNS void AS $$
BEGIN
    -- 테이블 비우기
    DELETE FROM lumi_product_sn;
    
    -- 대량 삽입 실행
    INSERT INTO lumi_product_sn (lumi_sn, time)
    SELECT 
        (value->>'lumi_sn')::TEXT, 
        COALESCE(value->>'time', '')::TEXT
    FROM jsonb_array_elements(p_rows);
END;
$$ LANGUAGE plpgsql;


-- =============================================================
-- [출하 동기화] production_records → shipped_devices
-- 생산 기록 저장 시 Solity SN을 출하 테이블에 동일 트랜잭션으로 기록한다.
-- 이 프로젝트는 K100 생산용이므로 model은 'K100' 고정.
-- =============================================================

-- 9. shipped_devices 구조 보강
--    기존 19,036행은 그대로 두고 컬럼만 추가한다.
ALTER TABLE shipped_devices ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE shipped_devices ADD COLUMN IF NOT EXISTS deleted_at TEXT DEFAULT NULL;
ALTER TABLE shipped_devices ADD COLUMN IF NOT EXISTS record_id BIGINT
    REFERENCES production_records(id) ON DELETE SET NULL;

-- sn 중복 방지 (동기화를 멱등하게 만들기 위해 필수)
ALTER TABLE shipped_devices DROP CONSTRAINT IF EXISTS shipped_devices_sn_key;
ALTER TABLE shipped_devices ADD CONSTRAINT shipped_devices_sn_key UNIQUE (sn);

CREATE INDEX IF NOT EXISTS idx_shipped_devices_record_id
    ON shipped_devices (record_id);

-- [권한] anon 키에는 읽기만 허용한다.
--   쓰기는 아래 SECURITY DEFINER RPC를 통해서만 이루어진다.
ALTER TABLE shipped_devices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on shipped_devices" ON shipped_devices;
DROP POLICY IF EXISTS "Read-only shipped_devices" ON shipped_devices;
CREATE POLICY "Read-only shipped_devices"
    ON shipped_devices FOR SELECT
    USING (true);

-- 테이블 레벨에서도 쓰기 권한 회수 (RLS와 이중 방어)
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON shipped_devices FROM anon, authenticated;
GRANT SELECT ON shipped_devices TO anon, authenticated;


-- 10. 생산 시각 문자열('YYYY-MM-DD HH:MM:SS')에서 출하 배치 정보를 유도하는 헬퍼
--     batch_id는 'YYMMDD', shipped_date는 기존 데이터 형식인 'YYYY/M/D'를 따른다.
CREATE OR REPLACE FUNCTION _shipped_batch_of(p_production_time TEXT)
RETURNS TABLE (batch_id TEXT, shipped_date TEXT) AS $$
DECLARE
    v_date DATE;
BEGIN
    v_date := substring(p_production_time FROM 1 FOR 10)::DATE;
    RETURN QUERY SELECT
        to_char(v_date, 'YYMMDD'),
        to_char(v_date, 'FMYYYY/FMMM/FMDD');
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- 11. RPC 함수(교체): 매칭 저장 시 shipped_devices까지 동일 트랜잭션으로 기록
CREATE OR REPLACE FUNCTION create_production_match(
    p_lumi_sn TEXT,
    p_solity_sn TEXT,
    p_production_time TEXT,
    p_operator_name TEXT,
    p_note TEXT
) RETURNS jsonb AS $$
DECLARE
    v_record_id BIGINT;
    v_batch RECORD;
    v_result jsonb;
BEGIN
    -- 1. production_records에 삽입
    INSERT INTO production_records (lumi_sn, solity_sn, production_time, operator_name, note)
    VALUES (p_lumi_sn, p_solity_sn, p_production_time, p_operator_name, p_note)
    RETURNING id INTO v_record_id;

    -- 2. used_sn_codes에 삽입
    INSERT INTO used_sn_codes (sn_value, record_id, sn_role)
    VALUES
        (p_lumi_sn, v_record_id, 'lumi'),
        (p_solity_sn, v_record_id, 'solity');

    -- 3. shipped_devices에 Solity SN 기록
    --    이미 존재하는 SN이면 배치/출하일 등 기존 출하 정보는 보존하고
    --    생산 기록과의 연결만 갱신한다(삭제되었던 행은 되살린다).
    SELECT * INTO v_batch FROM _shipped_batch_of(p_production_time);
    INSERT INTO shipped_devices (sn, model, batch_id, shipped_date, record_id)
    VALUES (p_solity_sn, 'K100', v_batch.batch_id, v_batch.shipped_date, v_record_id)
    ON CONFLICT (sn) DO UPDATE
        SET record_id = EXCLUDED.record_id,
            deleted_at = NULL;

    -- 4. 결과 반환값 구성
    v_result := jsonb_build_object(
        'id', v_record_id,
        'lumi_sn', p_lumi_sn,
        'solity_sn', p_solity_sn,
        'production_time', p_production_time,
        'operator_name', p_operator_name,
        'note', p_note
    );

    RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;


-- 12. RPC 함수(신규): 매칭 수정을 원자적으로 처리
--     기존 Python 코드는 UPDATE + DELETE + INSERT를 개별 호출해 원자성이 없었다.
CREATE OR REPLACE FUNCTION update_production_match(
    p_record_id BIGINT,
    p_lumi_sn TEXT,
    p_solity_sn TEXT,
    p_operator_name TEXT,
    p_note TEXT
) RETURNS jsonb AS $$
DECLARE
    v_row production_records%ROWTYPE;
    v_batch RECORD;
BEGIN
    UPDATE production_records
       SET lumi_sn = p_lumi_sn,
           solity_sn = p_solity_sn,
           operator_name = p_operator_name,
           note = p_note
     WHERE id = p_record_id
       AND deleted_at IS NULL
    RETURNING * INTO v_row;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    -- used_sn_codes 갱신
    DELETE FROM used_sn_codes WHERE record_id = p_record_id;
    INSERT INTO used_sn_codes (sn_value, record_id, sn_role)
    VALUES
        (p_lumi_sn, p_record_id, 'lumi'),
        (p_solity_sn, p_record_id, 'solity');

    -- Solity SN이 바뀐 경우 이전 출하 행은 연결 해제 후 소프트 삭제
    UPDATE shipped_devices
       SET deleted_at = to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD HH24:MI:SS'),
           record_id = NULL
     WHERE record_id = p_record_id
       AND sn <> p_solity_sn;

    SELECT * INTO v_batch FROM _shipped_batch_of(v_row.production_time);
    INSERT INTO shipped_devices (sn, model, batch_id, shipped_date, record_id)
    VALUES (p_solity_sn, 'K100', v_batch.batch_id, v_batch.shipped_date, p_record_id)
    ON CONFLICT (sn) DO UPDATE
        SET record_id = EXCLUDED.record_id,
            deleted_at = NULL;

    RETURN to_jsonb(v_row);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;


-- 13. RPC 함수(신규): 매칭 소프트 삭제를 원자적으로 처리
CREATE OR REPLACE FUNCTION delete_production_match(
    p_record_id BIGINT,
    p_deleted_at TEXT
) RETURNS BOOLEAN AS $$
DECLARE
    v_found BOOLEAN;
BEGIN
    UPDATE production_records
       SET deleted_at = p_deleted_at
     WHERE id = p_record_id
    RETURNING TRUE INTO v_found;

    IF NOT FOUND THEN
        RETURN FALSE;
    END IF;

    -- SN 재사용이 가능하도록 사용 이력에서 해제
    DELETE FROM used_sn_codes WHERE record_id = p_record_id;

    -- 출하 행도 함께 소프트 삭제
    UPDATE shipped_devices
       SET deleted_at = p_deleted_at
     WHERE record_id = p_record_id;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;


-- 13-1. SECURITY DEFINER 함수 실행 권한 명시
--   기본값은 PUBLIC 실행 허용이므로, 필요한 롤로만 좁힌다.
-- 내부 헬퍼는 REST API로 노출할 필요가 없다.
REVOKE ALL ON FUNCTION _shipped_batch_of(TEXT) FROM PUBLIC;

REVOKE ALL ON FUNCTION create_production_match(TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION update_production_match(BIGINT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION delete_production_match(BIGINT, TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION create_production_match(TEXT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION update_production_match(BIGINT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION delete_production_match(BIGINT, TEXT) TO anon, authenticated;


-- 14. 기존 생산 기록 백필 (재실행해도 안전)
--     이미 출하 테이블에 있는 SN은 기존 출하 정보를 유지한 채 연결만 맺는다.
INSERT INTO shipped_devices (sn, model, batch_id, shipped_date, record_id)
SELECT pr.solity_sn,
       'K100',
       b.batch_id,
       b.shipped_date,
       pr.id
  FROM production_records pr
 CROSS JOIN LATERAL _shipped_batch_of(pr.production_time) b
 WHERE pr.deleted_at IS NULL
ON CONFLICT (sn) DO UPDATE
    SET record_id = EXCLUDED.record_id,
        deleted_at = NULL;
